export const CREATE_BANNER_REQUEST = 'CREATE_BANNER_REQUEST'
export const CREATE_BANNER_SUCCESS =  'CREATE_BANNER_SUCCESS'
export const CREATE_BANNER_FAIL =  'CREATE_BANNER_FAILURE'
export const GET_BANNER_RESET = 'GET_BANNER_RESET'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'
