export const GET_ALL_CATEGORIES_REQUEST = "GET_ALL_CATEGORIES_REQUEST"
export const GET_ALL_CATEGORIES_SUCCESS = "GET_ALL_CATEGORIES_SUCCESS"
export const GET_ALL_CATEGORIES_FAIL = "GET_ALL_CATEGORIES_FAIL"

export const ADD_NEW_CATEGORY_REQUEST = "ADD_NEW_CATEGORY_REQUEST"
export const ADD_NEW_CATEGORY_SUCCESS = "ADD_NEW_CATEGORY_SUCCESS"
export const ADD_NEW_CATEGORY_FAIL = "ADD_NEW_CATEGORY_FAIL"
export const ADD_NEW_CATEGORY_RESET = "ADD_NEW_CATEGORY_RESET"

export const UPDATE_CATEGORY_REQUEST = "UPDATE_CATEGORY_REQUEST"
export const UPDATE_CATEGORY_SUCCESS = "UPDATE_CATEGORY_SUCCESS"
export const UPDATE_CATEGORY_FAIL = "UPDATE_CATEGORY_FAIL"
export const UPDATE_CATEGORY_RESET = "UPDATE_CATEGORY_RESET"

export const DELETE_CATEGORY_REQUEST = "DELETE_CATEGORY_REQUEST"
export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS"
export const DELETE_CATEGORY_FAIL = "DELETE_CATEGORY_FAIL"
export const DELETE_CATEGORY_RESET = "DELETE_CATEGORY_RESET"

export const ADMIN_CATEGORY_REQUEST = "ADMIN_CATEGORY_REQUEST"
export const ADMIN_CATEGORY_SUCCESS = "ADMIN_CATEGORY_SUCCESS"
export const ADMIN_CATEGORY_FAIL = "ADMIN_CATEGORY_FAIL"


export const CLEAR_ERRORS = "CLEAR_ERRORS"