export const ADD_USER_ORDER_REQUEST = "ADD_USER_ORDER_REQUEST"
export const ADD_USER_ORDER_SUCCESS = "ADD_USER_ORDER_SUCCESS"
export const ADD_USER_ORDER_FAIL = "ADD_USER_ORDER_FAIL"

export const GET_USER_ORDER_REQUEST = "GET_USER_ORDER_REQUEST"
export const GET_USER_ORDER_SUCCESS = "GET_USER_ORDER_SUCCESS"
export const GET_USER_ORDER_FAIL = "GET_USER_ORDER_FAIL"

export const GET_USER_ORDER_DETAILS_REQUEST = "GET_USER_ORDER_DETAILS_REQUEST"
export const GET_USER_ORDER_DETAILS_SUCCESS = "GET_USER_ORDER_DETAILS_SUCCESS"
export const GET_USER_ORDER_DETAILS_FAIL = "GET_USER_ORDER_DETAILS_FAIL"

export const ORDER_PAY_REQUEST = "ORDER_PAY_REQUEST"
export const ORDER_PAY_SUCCESS =  "ORDER_PAY_SUCCESS"
export const ORDER_PAY_FAIL = "ORDER_PAY_FAIL"
export const ORDER_PAY_RESET = "ORDER_PAY_RESET"


export const MY_ORDERS_REQUEST = 'MY_ORDERS_REQUEST'
export const MY_ORDERS_SUCCESS = 'MY_ORDERS_SUCCESS'
export const MY_ORDERS_FAIL = 'MY_ORDERS_FAIL'

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST'
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS'
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL'

export const ORDER_DELIVER_REQUEST =" ORDER_DELIVER_REQUEST"
export const ORDER_DELIVER_SUCCESS = "ORDER_DELIVER_SUCCESS"
export const ORDER_DELIVER_FAIL = "ORDER_DELIVER_FAIL"
export const ORDER_DELIVER_RESET = "ORDER_DELIVER_RESET"

export const DELETE_ORDER_REQUEST = 'DELETE_ORDER_REQUEST'
export const DELETE_ORDER_SUCCESS = 'DELETE_ORDER_SUCCESS'
export const DELETE_ORDER_RESET = 'DELETE_ORDER_RESET'
export const DELETE_ORDER_FAIL = 'DELETE_ORDER_FAIL'

export const GET_CUSTOMER_ORDER_REQUEST = "GET_CUSTOMER_ORDER_REQUEST"
export const GET_CUSTOMER_ORDER_SUCCESS = "GET_CUSTOMER_ORDER_SUCCESS"
export const GET_CUSTOMER_ORDER_FAIL = "GET_CUSTOMER_ORDER_FAIL"

export const UPDATE_CUSTOMER_ORDER_REQUEST = "UPDATE_CUSTOMER_ORDER_REQUEST"
export const  UPDATE_CUSTOMER_ORDER_SUCCESS = "UPDATE_CUSTOMER_ORDER_SUCCESS"
export const  UPDATE_CUSTOMER_ORDER_FAIL = "UPDATE_CUSTOMER_ORDER_FAIL"

export const UPDATE_ORDER_REQUEST = 'UPDATE_ORDER_REQUEST'
export const UPDATE_ORDER_SUCCESS = 'UPDATE_ORDER_SUCCESS'
export const UPDATE_ORDER_RESET = 'UPDATE_ORDER_RESET'
export const UPDATE_ORDER_FAIL = 'UPDATE_ORDER_FAIL'

export const ALL_ORDERS_REQUEST = 'ALL_ORDERS_REQUEST'
export const ALL_ORDERS_SUCCESS = 'ALL_ORDERS_SUCCESS'
export const ALL_ORDERS_FAIL = 'ALL_ORDERS_FAIL'
export const RESET_CART = 'RESET_CART'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'